version: "3.9"

services:
  app:
    user: root
    container_name: procure-app

    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_VITE_AUTH0_DOMAIN: ${PUBLIC_VITE_AUTH0_DOMAIN}
        PUBLIC_VITE_AUTH0_CLIENT_ID: ${PUBLIC_VITE_AUTH0_CLIENT_ID}
        PUBLIC_VITE_AUTH0_CALLBACK_URL: ${PUBLIC_VITE_AUTH0_CALLBACK_URL}
        PUBLIC_VITE_AUTH0_AUDIENCE: ${PUBLIC_VITE_AUTH0_AUDIENCE}
        PUBLIC_VITE_API_BASE_URL: ${PUBLIC_VITE_API_BASE_URL}

    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/procurement.db}

    ports:
      - "8080:8080"

    volumes:
      - ./data:/app/data


    restart: unless-stopped
