version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    volumes:
      - procure_data:/app/data
    restart: unless-stopped

volumes:
  procure_data:
