version: "3.9"

services:
  app:
    user: root
    container_name: procure-app

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/procurement.db}

    ports:
      - "8081:8080"

    volumes:
      - ./data:/app/data


    restart: unless-stopped
